# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        #CSS
        css_base_template:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/css/reset.css"
                - "%kernel.root_dir%/../vendor_assets/design/html/css/common.css"
                - "%kernel.root_dir%/../vendor_assets/design/html/css/form.css"
                - "%kernel.root_dir%/../vendor_assets/design/html/css/standard.css"
        css_table_template:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/css/table.css"

        #IMAGES
        img_arrow_circle:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/images/icons/fugue/arrow-circle.png"
        img_body_background:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/images/bg.png"
            output: images/bg.png
        img_information_icon:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/images/icons/fugue/information-ocre.png"
            output: images/icons/fugue/information-ocre.png
        img_separator:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/design/html/images/controls-bt-sep.png"
            output: images/controls-bt-sep.png

        #JS
        js_backbone:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/underscore/underscore.js"
                - "%kernel.root_dir%/../vendor_assets/backbone/backbone.js"
        js_jquery:
            inputs:
                - "%kernel.root_dir%/../vendor_assets/jquery/dist/jquery.js"
